### ISSUE TITLE
Not working with React-Native

### ISSUE THREAD

**Issue by ScoRoc** [CharlesStover/reactn-devtools#14]
ReactN works with React-Native no problem, but hooking up the dev tools doesn't seem to work. I added this to the top of my App.js file (which is the same file as `setGlobal`, `addReducers`, and my main `App()` function):

```
import addReactNDevTools from 'reactn-devtools';
addReactNDevTools();
```

Do I need to lift the `addReactNDevTools` function to a different file or will this not work with React-Native?

**Comment by CharlesStover** [comment]
ReactN Devtools hijacks Redux Devtools. I'm not positive that Redux Devtools supports React Native. If that's the case, ReactN Devtools would not support it either.

**Comment by ScoRoc** [comment]
Ah, I see - yea they don't by default. I was using remote-redux-devtools with reactn-devtools to try and connect them but didn't get it working. Didn't spend hours on it but as I was hoping it'd be an easy plug and play. remote-redux-devtools is an older package - there might be a better one that would connect better. Not sure.
